### ISSUE TITLE
published/updated not always populating (HTML to Atom)

### ISSUE THREAD

**Issue by gRegorLove** [snarfed/granary#480]
I'm using a [granary Atom feed](https://granary.io/url?input=html&output=atom&url=https%3A%2F%2Fgregorlove.com%2Fstream%2F&hub=https%3A%2F%2Fgregorlove.superfeedr.com%2F) of https://gregorlove.com/stream/ and some posts don't seem to convert the published or updated date. It appears to happen with RSVPs, bookmarks, and likes.

https://gregorlove.com/2023/01/im-probably-attending-homebrew-website-club/

```xml
<entry>
  <author>
    <activity:object-type>http://activitystrea.ms/schema/1.0/person</activity:object-type>
    <uri>https://gregorlove.com/</uri>
    <name>gRegor Morrill</name>
  </author>
  <activity:object-type>http://activitystrea.ms/schema/1.0/event</activity:object-type>
  <id>https://gregorlove.com/2023/01/im-probably-attending-homebrew-website-club/</id>
  <title>Iâ€™m probably attending </title>
  <content type="xhtml">
    <div xmlns="http://www.w3.org/1999/xhtml">
      <p>Iâ€™m <data class="p-rsvp" value="maybe">probably</data> attending <a class="u-in-reply-to h-event" href="https://events.indieweb.org/2023/01/homebrew-website-club-pacific-MKOZpT2yDqpU">Homebrew Website Club - Pacific</a> tonight at 6PM Pacific.</p>
    </div>
  </content>
  <link rel="alternate" type="text/html" href="https://gregorlove.com/2023/01/im-probably-attending-homebrew-website-club/" />
  <link rel="ostatus:conversation" href="https://gregorlove.com/2023/01/im-probably-attending-homebrew-website-club/" />
  <activity:verb>http://activitystrea.ms/schema/1.0/rsvp-maybe</activity:verb>
  <activity:object>https://events.indieweb.org/2023/01/homebrew-website-club-pacific-MKOZpT2yDqpU</activity:object>
  <published></published>
  <updated></updated>
  <link rel="self" type="application/atom+xml" href="https://gregorlove.com/2023/01/im-probably-attending-homebrew-website-club/" />
</entry>
```

Other posts currently in the stream this happens with:
* Like: https://gregorlove.com/2023/01/star-dave-millar/
* Bookmark: https://gregorlove.com/2023/01/bookmarked-make-your-own/
* Like: https://gregorlove.com/2023/01/star-taking-a-break/

**Comment by snarfed** [comment]
Hmm! Thanks for reporting, will look.

**Comment by snarfed** [comment]
Fixed, thanks again!

**Comment by gRegorLove** [comment]
@snarfed Thanks! [This bookmark](https://gregorlove.com/2023/01/bookmarked-make-your-own/) is still showing blank, but the others are working now. Is it cached?

**Comment by snarfed** [comment]
Argh, true, thanks for following up. Reopening.

**Comment by snarfed** [comment]
Fixed!
