### ISSUE TITLE
atom validation errors

### ISSUE THREAD

**Issue by snarfed** [snarfed/granary#93]
evidently the atom we emit doesn't always validate. e.g. converting scraped instagram to atom gives us these errors from https://validator.w3.org/feed/ :

```
line 16, column 28: updated must be an RFC-3339 date-time: 2016-05-31T16:21:12 [help]
  <updated>2016-05-31T16:21:12</updated>

line 74, column 32: published must be an RFC-3339 date-time: 2016-05-31T16:21:12 (24 occurrences) [help]
  <published>2016-05-31T16:21:12</published>

line 75, column 30: updated must be an RFC-3339 date-time: 2016-05-31T16:21:12 (24 occurrences) [help]
  <updated>2016-05-31T16:21:12</updated>

line 80, column 4: Undefined entry element: georss:featureName (11 occurrences) [help]
  <georss:featureName>U.S. Citizenship and Immigration Services</georss:fe ...
```

thanks @cleverdevil for reporting!

**Comment by snarfed** [comment]
@cleverdevil i'm still working on this, but i fixed the most egregious problem, which i suspect will fix your reader. feel free to retry!

**Comment by cleverdevil** [comment]
So, this does seem to have made things work better, though it still doesn't properly import into Reader Self (https://readerself.com). For some reason, after initial attempt to import, it lists out a bunch of items in the feed itself to select for a URL for the feed. Very odd. It also complains about the URI being too long (the MySQL field is too short... sigh).

If I cheat, and go into the database, and use a goo.gl shortened version of the link, it imports fine, and reads the posts (mostly).

That said, this mostly seems like an issue with Reader Self, not with instagram-to-atom. But, I thought I'd detail the experience here!

**Comment by snarfed** [comment]
thanks for the details! definitely good to have them documented somewhere.

**Comment by aribn** [comment]
I opened an [issue on twitter-atom](https://github.com/snarfed/twitter-atom/issues/5) earlier today, but think that it may be more useful to mention here.

The atom feed returned for Twitter list `aribadernatal/my-tweets` is invalid according to the [W3C feed validation service](https://validator.w3.org/feed/), and is not being recognized by [FeedWordPress](https://wordpress.org/plugins/feedwordpress/). 

The line that seems to be responsible for the error (part of the text of a tweet in the feed) contains an unescaped closing quote mark (`’`), which seems like it might be the culprit.

**Comment by snarfed** [comment]
thanks again for the thorough investigation and details @aribn! this is indeed a good place to collect validation problems.

your hunch about the closing quote mark made sense to me too, but it might not be that after all. i'm removing that character entirely now (temporarily), but the validator still shows the same error.

i'm also encoding as utf-8 and including an encoding declaration in the opening XML tag, which seems like it should be enough, but who knows. maybe Atom is stricter somehow, or maybe it's unhappy inside the `<div xmlns="http://www.w3.org/1999/xhtml">`? ¯\\\_(ツ)\_/¯

**Comment by snarfed** [comment]
found it. i wasn't escaping `&`s in links in quote tweets. fixed in 1435ad81e849357f81e18b88cf79e06b23dddd1c.
